@protocol = http
@host = 127.0.0.1
@port = 8082
@baseUrl = {{protocol}}://{{host}}:{{port}}

###

# @name updateConfig
POST {{baseUrl}}/mock
Content-Type: application/json

{
  "activeVariant": "Test Variant",
  "recordResponses": true
}

###

# @name resetConfig
DELETE {{baseUrl}}/mock

###

###

# @name getConfig
GET {{baseUrl}}/mock

###

# @name setVariant
POST {{baseUrl}}/mock/activeVariant
Content-Type: application/json

{
  "activeVariant": "Test Variant"
}

###

# @name deleteVariant
DELETE {{baseUrl}}/mock/activeVariant

###

# @name getVariant
GET {{baseUrl}}/mock/activeVariant

###

# @name setRecordResponses
POST {{baseUrl}}/mock/recordResponses
Content-Type: application/json

{
    "recordResponses": true
}

###

# @name deleteRecordResponses
DELETE {{baseUrl}}/mock/recordResponses

###

# @name getRecordResponses
GET {{baseUrl}}/mock/recordResponses

###

# @name sampleRequest
GET {{baseUrl}}/test

###

# @name sampleRequestWithQuery
GET {{baseUrl}}/test?query=sample

### Sample Requests for testing response recording

@catFactsUrl = https://cat-fact.herokuapp.com

# @name
GET {{baseUrl}}/facts/random?animal_type=cat&amount=5

###

GET {{baseUrl}}/facts/59664b1f474ba80020ef8592
    ?renew=ab
