AppConfiguration:
  android:
    app: android_sample.apk
    automationName: UIAutomator2
    appPackage: com.swaglabsmobileapp
    appWaitActivity: com.swaglabsmobileapp.MainActivity

  ios:
    app: ios_sample.ipa
    automationName: XCUITest
    xcodeOrgId: 5HMJW6N276
    xcodeSigningId: iPhone Developer
    bundleIdentifier: org.reactjs.native.example.SwagLabsMobileApp

  web:
    address: https://www.google.com
    headless: true

  web-mobile:
    address: https://www.google.com

Appium:
  port: 4273
  systemPort: 8200
  username: ${SAUCE_USERNAME}
  accessKey: ${SAUCE_ACCESS_KEY}

MockServer:
  host: 127.0.0.1
  port: 53209
